export default [
    { message: "It is certain.", color: "green" },
    { message: "It is decidedly so.", color: "green" },
    { message: "Without a doubt.", color: "green" },
    { message: "Yes - definitely.", color: "green" },
    { message: "You may rely on it.", color: "green" },
    { message: "As I see it, yes.", color: "green" },
    { message: "Most likely.", color: "green" },
    { message: "Outlook good.", color: "green" },
    { message: "Yes.", color: "green" },
    { message: "Signs point to yes.", color: "goldenrod" },
    { message: "Reply hazy, try again.", color: "goldenrod" },
    { message: "Ask again later.", color: "goldenrod" },
    { message: "Better not tell you now.", color: "goldenrod" },
    { message: "Cannot predict now.", color: "goldenrod" },
    { message: "Concentrate and ask again.", color: "goldenrod" },
    { message: "Don't count on it.", color: "red" },
    { message: "My reply is no.", color: "red" },
    { message: "My sources say no.", color: "red" },
    { message: "Outlook not so good.", color: "red" },
    { message: "Very doubtful.", color: "red" },
  ]